Result page
HackYourFuture-CPH/simply-name.it pull request #155
Opened 2021-08-11 15:30 UTC by dinythomas89

# Description

Creating the result page
Fixes #76 

# How to test?

npm run dev and http://localhost:3000/boards/1/result

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

2021-08-24 15:35 UTC, senner007 commented
@Diny
Hi :)
Is this ready for merge?

2021-08-25 11:49 UTC, dinythomas89 commented
Hi Niels @senner007 , I think its all set.its functioning now and candidate name is also centerd

2021-08-25 13:09 UTC, senner007 requested changes
This is a no go for me, sorry.
We have to reuse the cardDecorator to not duplicate logic. Please see #225
Also the results page should be in its own authenticated route with /results/:boardId. See the slack post

2021-08-26 11:08 UTC, senner007 commented on src/client/containers/ResultPage/ResultPage.container.js
> +  const onArrowButtonClick = () => {
I assume you are going back to a board with a specific id here

2021-08-26 11:12 UTC, senner007 commented on src/client/containers/ResultPage/ResultPage.container.js
> +        throw new Error(error);
Throwing an error directly in the component will not really do anything. This is unfortunate actually since that would make error handling more straight forward. Instead you must create an error state and then throw in the setErrorState

2021-08-26 11:15 UTC, senner007 commented on src/client/containers/ResultPage/ResultPage.container.js
> +        throw new Error(error);
Sorry, you must await the fetchinResults in a try catch and then set the error in that catch

2021-08-27 08:48 UTC, senner007 commented on src/server/seeds/production/01_users.js
> +  // Deletes ALL existing entries
These are unrelated changes

2021-08-27 08:48 UTC, senner007 commented on src/client/containers/ResultPage/ResultPage.styles.css
> +* {
These selectors are too global

2021-08-27 18:21 UTC, senner007 commented on src/client/containers/ResultPage/ResultPage.container.js
> +        setError(e);
Great 👍
Can you throw an ApiError here in setError? As seen on slack. Then merge

2021-08-27 18:48 UTC, senner007 commented on src/client/containers/ResultPage/ResultPage.styles.css
> +* {
Nevermind, ApiError is not in the codebase yet

2021-08-27 18:48 UTC, merged