Get candidates endpoint
HackYourFuture-CPH/simply-name.it pull request #157
Opened 2021-08-11 20:52 UTC by DarinkaGM

# Description

Endpoint to get all the candidates from a board

Fixes  #64

# How to test?

You can test out in Swagger documentation: http://localhost:3000/api/documentation/#/Members/get_users__userId__boards__boardId__members

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

2021-08-15 08:14 UTC, DarinkaGM commented on src/server/api/routes/candidates.router.js
> +});
Makes sense :)

2021-08-15 12:08 UTC, Rasim-Deniz approved these changes

2021-08-15 13:52 UTC, dpfernandes requested changes

2021-08-15 13:52 UTC, dpfernandes commented on src/server/api/controllers/candidates.controller.js
> +    throw new InvalidIdError(`Board not found`);
Write _InvalidEntryError_ instead of _InvalidIdError_

2021-08-15 13:58 UTC, Midnighter requested changes
The code already looks quite good. I would change the database query and I agree on the validation, that should be added.

2021-08-15 13:58 UTC, Midnighter commented on src/server/api/controllers/candidates.controller.js
> +    .join('boards', 'candidates.boardId', '=', 'boards.id')
You don't need to join on the boards table, the `boardId` is already present on the other tables and you don't need other information from that table.

2021-08-15 13:58 UTC, Midnighter commented on src/server/api/controllers/candidates.controller.js
> +    .select('candidates.name', 'ballots.rank')
Please also select the `candidateId` it will be needed for further communication.

2021-08-15 13:58 UTC, Midnighter commented on src/server/api/controllers/candidates.controller.js
> +  const candidates = await knex('candidates')
The title of the issue is a bit misleading, it should probably be called get ballot. So conceptually, I would select from the `ballots` table where user and board ID are as in the request, and then join the names from the `candidates` table.

2021-08-17 10:52 UTC, Midnighter commented
I don't see the validation yet but all the rest looks excellent 🙂

2021-08-18 13:02 UTC, DarinkaGM commented
> I don't see the validation yet but all the rest looks excellent 🙂
It's added now :)

2021-08-18 13:08 UTC, Midnighter commented
Hmm, not quite but I suppose we need the Firebase integration first. Basically, we need to check first if the `userId` provided in the URL path corresponds to the user identified by the Firebase token. So, validating that the user is who they claim to be. Otherwise, with a valid token, you could check anyone else's data. But we don't have Firebase yet so it's good.

2021-08-18 13:08 UTC, Midnighter approved these changes

2021-08-19 16:33 UTC, senner007 commented
> Hmm, not quite but I suppose we need the Firebase integration first. Basically, we need to check first if the `userId` provided in the URL path corresponds to the user identified by the Firebase token. So, validating that the user is who they claim to be. Otherwise, with a valid token, you could check anyone else's data. But we don't have Firebase yet so it's good.

We have authentication working now. All requests will be piped through the authenticate middleware by calling router.use(authenticate)

2021-08-19 16:39 UTC, senner007 approved these changes
✔

2021-08-19 16:44 UTC, dpfernandes approved these changes

2021-08-19 16:58 UTC, merged