Feature/new board page
HackYourFuture-CPH/simply-name.it pull request #212
Opened 2021-08-24 10:28 UTC by dinythomas89

# Description

Creating a page to add a new board for a specific user

Fixes #84

# How to test?

npm run dev 

# Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [ ] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [ ] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [ ] This PR is ready to be merged and not breaking any other functionality

2021-08-29 12:01 UTC, senner007 requested changes
A few initial comments without looking at the code:
I can see its creating a board, but I get no feedback once the board is created.
Also, I don't see the members for the board in the db?

2021-08-30 10:00 UTC, dinythomas89 commented
Hi Niels, now the members can be added
But I am little confused how to implement the feedback when board is created. Did you mean an alert message?

2021-08-30 10:30 UTC, senner007 commented
> Hi Niels, now the members can be added
> But I am little confused how to implement the feedback when board is created. Did you mean an alert message?

Great 👍
I think its better with a message saying that the board is added. Old school alerts are not used anymore

2021-08-30 17:29 UTC, dinythomas89 commented
> > Hi Niels, now the members can be added
> > But I am little confused how to implement the feedback when board is created. Did you mean an alert message?
> 
> Great 👍
> I think its better with a message saying that the board is added. Old school alerts are not used anymore

Hi Niels, I tried to display a message in below all the components when the board is created and its functioning now

2021-08-31 22:34 UTC, senner007 approved these changes
Great 👍! 
Looks nice and seems to get the job done
You need to throw an ApiError also. See the other prs. Now or create an issue for it
Check the comment about the css classes and merge

2021-08-31 22:34 UTC, senner007 commented on src/client/containers/CreateBoardPage/CreateBoardPage.styles.css
> +.board-container {
Change the css rules please
add 'new-board-' prefix to each

2021-09-01 11:03 UTC, merged