Passed userId as Props and removed hard coded values from delete modal
HackYourFuture-CPH/simply-name.it pull request #230
Opened 2021-08-26 11:40 UTC by SlaviaF

# Description

Adjustments for #88. Props passed for the userId, and hard coded values are removed from the code .

Fixes # 88

# How to test?

to incorporate error handling from the parent component:
1. const [error, setError] = useState(null);

2. const deleteErrorHandler = (err) => {
    setError(err);
  };
3. Pass the error handler as props with the rest of the props
{modalVisibility && (
            <DeleteBoardModal
              boardInfo={boardInfo}
              modalVisibility={modalVisibility}
              setModalVisibility={setModalVisibility}
              errorPageOnDelete={errorPageOnDelete}
            />
          )}

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

2021-08-26 11:51 UTC, senner007 requested changes
Looking good
You also need a deleteHandler here. In here you await the delete function and rethrow the error in a setErrorState function

2021-08-26 11:52 UTC, senner007 commented
> Looking good
> You also need a deleteHandler here. In here you await the delete function and rethrow the error in a setErrorState function

see #155

2021-08-26 17:25 UTC, SlaviaF commented
> > Looking good
> > You also need a deleteHandler here. In here you await the delete function and rethrow the error in a setErrorState function
> 
> see #155


I have called a function(deleteErrorHandler) in the fetch  The function and the state will be passed in the parent component (as mentioned in the PR description). Is it the right way.

2021-08-28 15:37 UTC, senner007 requested changes

2021-08-28 15:37 UTC, senner007 commented on src/client/containers/DeleteBoardModal/DeleteBoardModal.container.js
> +      }
I think we're good if the alert is removed. You will have to find an other way to notify the user

2021-08-28 15:56 UTC, senner007 requested changes

2021-08-28 15:56 UTC, senner007 commented on src/client/containers/DeleteBoardModal/DeleteBoardModal.container.js
> +      deleteErrorHandler(error);
I don't see why you need to pass down a deleteHandler here.
You need to throw throw an ApiError in the catch function if its a general error that is not be handled in this component

2021-08-28 20:14 UTC, senner007 requested changes

2021-08-28 20:14 UTC, senner007 commented on src/client/containers/DeleteBoardModal/DeleteBoardModal.container.js
> +      setError(() => {
You need to get the error from the catch here. 
catch (error) {

then pass the message and the status code to the ApiError

2021-08-29 11:50 UTC, senner007 approved these changes
✔

2021-08-29 11:50 UTC, senner007 commented on src/client/containers/DeleteBoardModal/DeleteBoardModal.container.js
> +        throw new ApiError(err.message, err.statusCode);
Great 👍
We really need a global fetch method to do this for us.
Try and provoke an error and check if its working. Merge when done

2021-08-29 12:54 UTC, merged