Add loading state to Board Page
HackYourFuture-CPH/simply-name.it pull request #254
Opened 2021-08-30 15:02 UTC by Rasim-Deniz

# Description

Added loading state to Board Page to control the added or deleted candidates.

Fixes #253 

# How to test?

npm run dev

# Checklist

- [X] I have performed a self-review of my own code
- [X] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [X] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [X] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [X] This PR is ready to be merged and not breaking any other functionality

2021-08-30 15:03 UTC, Rasim-Deniz commented
@senner007 Niels, I tried to implement following the way you mentioned but I'm getting this error at the moment. Could you please have a look what is missing? 
![adafaadas](https://user-images.githubusercontent.com/75583909/131360482-5910b644-f4ea-4b70-965c-34126a5ee3cb.PNG)

2021-08-30 17:16 UTC, Rasim-Deniz commented
> @senner007 Niels, I tried to implement following the way you mentioned but I'm getting this error at the moment. Could you please have a look what is missing?
> ![adafaadas](https://user-images.githubusercontent.com/75583909/131360482-5910b644-f4ea-4b70-965c-34126a5ee3cb.PNG)

This error is gone but I don't get the candidates.

2021-08-30 17:19 UTC, Saidemm commented
> @senner007 Niels, I tried to implement following the way you mentioned but I'm getting this error at the moment. Could you please have a look what is missing?
> ![adafaadas](https://user-images.githubusercontent.com/75583909/131360482-5910b644-f4ea-4b70-965c-34126a5ee3cb.PNG)

The error is fixed.

2021-08-30 18:09 UTC, Rasim-Deniz commented
> > @senner007 Niels, I tried to implement following the way you mentioned but I'm getting this error at the moment. Could you please have a look what is missing?
> > ![adafaadas](https://user-images.githubusercontent.com/75583909/131360482-5910b644-f4ea-4b70-965c-34126a5ee3cb.PNG)
> 
> This error is gone but I don't get the candidates now.

Everything is fixed thanks to Hanieh and Saide! @senner007 Please take a look and let us merge 😄

2021-08-30 23:46 UTC, senner007 requested changes
This duplicates the logic in the other board pr

2021-08-31 14:24 UTC, Rasim-Deniz commented
> This duplicates the logic in the other board pr

Conflicts are solved. Can you check if there is any problem? We need this.

2021-08-31 16:06 UTC, senner007 requested changes
few changes

2021-08-31 16:06 UTC, senner007 commented on src/client/containers/BoardPage/BoardPageComponents/CandidateList/CandidateListPostDeadline.js
> +export default function CandidateListPostDeadline({ displayDelete }) {
You are still showing the error here. In the other pr you removed it after Slavias review

2021-08-31 16:06 UTC, senner007 commented on src/client/containers/UseHooks/useCandidates.js
>          setError(
Same thing with the ApiError here also

2021-08-31 17:06 UTC, senner007 approved these changes
✔

2021-08-31 17:07 UTC, merged